STRIPE_SECRET_KEY = '{{stripe_secret_key}}'
STRIPE_KEY = '{{stripe_key}}'
SLACK_KEY = '{{slack_key}}'
SLACK_SECRET = '{{slack_secret}}'
SLACK_VERIFICATION_TOKEN = '{{slack_verification_token}}'
SECRET_SESSION_KEY = '{{secret_session_key}}'
PREFERRED_URL_SCHEME = 'https'
SESSION_COOKIE_DOMAIN = '.spacewiki.io'
SENTRY_DSN = '{{sentry_dsn}}'
IO_DOMAIN = 'spacewiki.io'
IO_SCHEME = 'https'

SUBSPACE_SLACK_KEY = SLACK_KEY
SUBSPACE_SLACK_SECRET = SLACK_SECRET
SUBSPACE_SLACK_VERIFICATION_TOKEN = SLACK_SECRET
SUBSPACE_SECRET_KEY = SECRET_SESSION_KEY
SUBSPACE_DATABASE_NAME = 'spacewiki_site_%(slack_id)s'
SUBSPACE_DATABASE_URL = 'postgres://postgres:postgres@localhost/' + SUBSPACE_DATABASE_NAME
SUBSPACE_UPLOAD_PATH = '/srv/spacewiki/uploads/%(domain)s'
